import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { writeFile, copyFile } from 'node:fs/promises';
const require=createRequire(new URL('../app/desktop/package.json',import.meta.url));
await require('esbuild').build({entryPoints:['atlas.ts'],outdir:'public/atlases',bundle:true,format:'esm',minify:true,loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]'});
for(const name of ['enso','photonic'])await writeFile(`public/atlases/${name}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${name==='enso'?'ENSO prediction':'Photonic computing'} — ThinkReader</title><link rel="stylesheet" href="atlas.css"><link rel="stylesheet" href="layout.css"></head><body data-atlas="${name}"><header><nav id="modes" aria-label="Research views"></nav><button id="fit">Fit</button><button id="arrange">Arrange</button><button id="expand" aria-label="Expand atlas">⤢</button><label class="clusters">Clusters <output id="cluster-count">3</output><input id="clusters" aria-label="Number of clusters" type="range" min="0" max="20" value="3"></label></header><main><div class="graph-wrap"><svg id="hulls" aria-hidden="true"></svg><div id="graph" role="application" aria-label="Interactive research graph"></div></div><article id="note" tabindex="0"></article></main><footer id="legend"></footer><script type="module" src="atlas.js"></script></body></html>`);
await require('esbuild').build({entryPoints:['mindmap.ts'],outdir:'public/mindmaps',bundle:true,format:'esm',minify:true,loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]'});
for(const name of ['attention','xro'])await writeFile(`public/mindmaps/${name}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThinkReader — Mindmap</title><link rel="stylesheet" href="mindmap.css"><link rel="stylesheet" href="layout.css"></head><body data-mindmap="${name}"><div id="viewport" role="region" aria-label="Interactive mindmap" tabindex="0"><div id="world"><svg id="edges"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0 L8 4 L0 8 Z"/></marker></defs></svg></div></div><script type="module" src="mindmap.js"></script></body></html>`);

await require('esbuild').build({entryPoints:['document.ts'],outdir:'public/documents',bundle:true,format:'esm',minify:true,loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]'});
await copyFile('../app/desktop/node_modules/pdfjs-dist/build/pdf.worker.min.mjs','public/documents/pdf.worker.min.mjs');
const demoFonts={name:'demo-font-subset',setup(build){build.onResolve({filter:/SourceHanSansCN-VF\.ttf\.woff2$/},()=>({path:fileURLToPath(new URL('./fonts/ThinkReaderGallerySans-Latin.woff2',import.meta.url))}));}};
await copyFile('../app/desktop/public/licenses/SourceHanSans-OFL.txt','public/documents/fonts/OFL.txt');
await require('esbuild').build({plugins:[demoFonts],entryPoints:['feature-demo.ts'],jsx:'automatic',alias:{'react/jsx-runtime':require.resolve('react/jsx-runtime'),'react':require.resolve('react'),'react-dom':require.resolve('react-dom')},loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]',outdir:'public/documents',bundle:true,format:'esm',minify:true});
await require('esbuild').build({plugins:[demoFonts],entryPoints:['agents-demo.tsx'],jsx:'automatic',alias:{'react/jsx-runtime':require.resolve('react/jsx-runtime'),'react':require.resolve('react'),'react-dom':require.resolve('react-dom')},outdir:'public/documents',bundle:true,format:'esm',minify:true,loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]'});
await writeFile('public/documents/agents-demo.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThinkReader Agents demo</title><link rel="stylesheet" href="agents-demo.css"><link rel="stylesheet" href="agents-demo-layout.css"></head><body><div id="root"></div><script type="module" src="agents-demo.js"></script></body></html>`);
await writeFile('public/documents/feature-demo.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThinkReader interactive demo</title><link rel="stylesheet" href="feature-demo.css"><link rel="stylesheet" href="feature-demo-layout.css"></head><body><span id="status" hidden></span><button id="pause" aria-label="Pause demo"><svg viewBox="0 0 24 24"><path d="M8 5v14M16 5v14"/></svg></button><button id="replay" aria-label="Restart demo"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 10a8 8 0 1 1 1 8M4 4v6h6"/></svg></button><main><section id="paper"><div id="excerpt"><canvas aria-label="Original paper abstract"></canvas></div><button id="cite">Discuss this passage</button><div id="tasks"></div></section><section id="agent"><div>Agents</div><div id="messages" role="log" aria-live="polite"></div><form><textarea aria-label="Demo instruction" placeholder="Ask your agents…" maxlength="2000"></textarea><button aria-label="Send demo instruction">↑</button></form></section></main><script type="module" src="feature-demo.js"></script></body></html>`);
for(const name of ['attention-summary','xro-summary','xro-report'])await writeFile(`public/documents/${name}.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThinkReader — Note and source</title><link rel="stylesheet" href="document.css"><link rel="stylesheet" href="layout.css"></head><body data-document="${name}"><main><article id="note" aria-label="Research note"></article><div id="source-wrap"><div id="source" aria-label="Original PDF page" tabindex="0"><div id="page"><canvas></canvas><div id="mark"></div></div></div><output id="page-number"></output></div></main><script type="module" src="document.js"></script></body></html>`);

await require('esbuild').build({entryPoints:['codebase.ts'],outdir:'public/documents',bundle:true,format:'esm',minify:true,loader:{'.woff':'file','.woff2':'file','.ttf':'file'},assetNames:'fonts/[name]-[hash]'});
await writeFile('public/documents/attention-codebase.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ThinkReader — Reproduction workspace</title><link rel="stylesheet" href="codebase.css"><link rel="stylesheet" href="codebase-layout.css"></head><body><main><section id="project"><nav id="files" aria-label="Project files"></nav><article id="note" tabindex="0"></article></section><section id="agent"><iframe class="real-agents" title="ThinkReader Agents" src="agents-demo.html?pane=1&amp;paper=attention&amp;agent=Coder&amp;command=codebase"></iframe></section></main><script type="module" src="codebase.js"></script></body></html>`);
